version: '3'

services:

    server:
        container_name: server
        build: .
        depends_on:
            - db
        ports:
            - 3000:3000
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            SYNC_DB: ${SYNC_DB}
            DATABASE_TYPE: ${DATABASE_TYPE}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
        # links:
        #     - db
        env_file:
            - .env.docker

    db:
        container_name: db
        image: postgres:13
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - ./pg_data:/var/lib/postgresql/data/
            - ./seed:/docker-entrypoint-initdb.d/
            #- ./seed/seed.sql:/usr/lib/postgresql/13/bin/seed.sql
        env_file:
            - .env.docker

# volumes:
#     pg_data: