image: node:10.16

pipelines:
  branches:
    development:
      - step:
          name: Build and export to static files
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - npm install
            - npm run build
            - npm run export
          artifacts:
            - out/**
      - step:
          name: Deploy files to AWS S3
          deployment: staging
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: "$AWS_DEFAULT_REGION"
                USERPOOL_ID: $USERPOOL_ID
                USERPOOL_REGION: $USERPOOL_REGION
                USERPOOL_WEBCLIENT_ID: $USERPOOL_WEBCLIENT_ID
                S3_BUCKET: "$AWS_S3_BUCKET"
                LOCAL_PATH: "out"
                ACL: "public-read"
                CACHE_CONTROL: "max-age=3600"
                EXPIRES: "2020-10-01T00:00:00+00:00"
                DELETE_FLAG: "true"
                EXTRA_ARGS: "--follow-symlinks --quiet"